# Generated by Django 4.2.14 on 2024-08-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('apelido', models.CharField(help_text='Define o Apelido (Nome) da Máquina', max_length=250)),
                ('serie', models.IntegerField(help_text='Define o Número de Série da Máquina', unique=True)),
                ('tipo', models.CharField(help_text='Define o Tipo da Máquina', max_length=250)),
                ('fabricante', models.CharField(blank=True, help_text='Define o Fabricante da Máquina', max_length=250)),
                ('modelo', models.CharField(help_text='Define o Fabricante da Máquina', max_length=250)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1, help_text='Define o Status da Máquina, por Padrão Ativa (1)')),
                ('data', models.DateField(help_text='Define o Data da Instalação da Máquina')),
                ('custo', models.FloatField(blank=True, help_text='Define o Custo da Máquina')),
                ('local', models.CharField(blank=True, help_text='Define onde a Máquina foi Instalda - Local/Setor', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Especificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltagem', models.IntegerField(choices=[(110, '110V'), (220, '220V'), (240, '240V'), (380, '380V'), (415, '415V'), (440, '440V'), (480, '480V'), (600, '600V')], help_text='Define a voltagem da Máquina')),
                ('controle', models.IntegerField(choices=[(0, 'Manual'), (1, 'Automatico'), (2, 'Hibrido')], default=1, help_text='Define o Tipo de Controle da Máquina')),
                ('peso', models.FloatField(blank=True, help_text='Define o Peso da Máquina')),
                ('velocidade', models.IntegerField(blank=True, help_text='Define a Velocidade da Máquina')),
                ('potencia', models.IntegerField(blank=True, help_text='Define a Potencia da Máquina')),
                ('altura', models.FloatField(blank=True, help_text='Define o Peso da Máquina')),
                ('largura', models.FloatField(blank=True, help_text='Define a Velocidade da Máquina')),
                ('profundidade', models.FloatField(blank=True, help_text='Define a Potencia da Máquina')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.maquina')),
            ],
        ),
    ]
