# Generated by Django 4.2.14 on 2024-08-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('apelido', models.CharField(help_text='Define o Apelido (Nome) da Máquina', max_length=250)),
                ('dataFabricacao', models.DateField(help_text='Define o Data da Fabricação da Máquina')),
                ('numeroSerie', models.CharField(help_text='Define o Número de Série da Máquina', max_length=10, unique=True)),
                ('dataStartup', models.DateField(help_text='Define o Data da Instalação da Máquina')),
                ('custo', models.FloatField(blank=True, help_text='Define o Custo da Máquina')),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1, help_text='Define o Status da Máquina, por Padrão Ativa (1)')),
                ('inputPower', models.IntegerField(choices=[(480, '480Vac'), (460, '460Vac'), (440, '440Vac'), (415, '415Vac'), (400, '400Vac'), (380, '380Vac'), (240, '240Vac'), (220, '220Vac'), (208, '208Vac')], help_text='Define a Tensão de Entrada da Máquina')),
                ('instaledPower', models.IntegerField(help_text='Define a Tensão Instalada pelo Cliente')),
                ('pressao', models.IntegerField(help_text='Define a Pressão Instalada pelo Cliente')),
                ('altura', models.FloatField(help_text='Define a Altura da Máquina')),
                ('largura', models.FloatField(help_text='Define a Largura da Máquina')),
                ('comprimento', models.FloatField(help_text='Define o Comprimento da Máquina')),
                ('forno', models.FloatField(help_text='Define o Tamanho do Forno')),
                ('modelo', models.ForeignKey(help_text='Define o Modelo da Máquina', on_delete=django.db.models.deletion.CASCADE, to='modelos.modelos')),
            ],
        ),
    ]
