# Generated by Django 4.2.14 on 2024-08-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='numeroSerie',
            field=models.CharField(help_text='Define o Número de Série da Máquina', max_length=10, unique=True),
        ),
    ]
